# Generated by Django 5.0.1 on 2024-01-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=240, verbose_name='Street')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
            ],
        ),
    ]
