# Generated by Django 5.0.1 on 2024-01-07 22:12

from django.db import migrations

def create_data(apps,schema_editor):
    Location=apps.get_model('travel_agency_app','Location')
    Location(street="Glavna",number="1",city="Katunitsa",country="Bulgaria").save()

class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
