# Generated by Django 5.0.1 on 2024-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0003_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='location',
            field=models.IntegerField(verbose_name='Location'),
        ),
    ]
