# Generated by Django 5.0.1 on 2024-01-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0004_alter_holiday_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.location'),
        ),
    ]
