# Generated by Django 5.0.1 on 2024-01-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0005_alter_holiday_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=240, verbose_name='Contact name')),
                ('phoneNumber', models.CharField(max_length=40, verbose_name='Phone Number')),
                ('holiday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.holiday')),
            ],
        ),
    ]
